
console.log('1. Importing path/fs...');
import path from 'path';
import fs from 'fs';
console.log('2. Importing express/cors...');
import express from 'express';
import cors from 'cors';
console.log('3. Importing helmet/compression...');
import helmet from 'helmet';
import compression from 'compression';
console.log('4. Importing http/socket.io...');
import { createServer } from 'http';
import { Server } from 'socket.io';
console.log('5. Importing environment...');
import { env } from './src/config/environment';
console.log('6. Importing logger...');
import { logger, apiLogger } from './src/utils/logger';
console.log('7. Importing errorHandler...');
import { errorHandler } from './src/middleware/errorHandler';
console.log('8. Importing requestLogger...');
import { requestLogger } from './src/middleware/requestLogger';
console.log('9. Importing cacheManager...');
import { cacheManager } from './src/services/cacheManager';
console.log('10. Importing historianConnection...');
import { getHistorianConnection } from './src/services/historianConnection';
console.log('11. Importing schedulerService...');
import { schedulerService } from './src/services/schedulerService';
console.log('12. Importing emailService...');
import { emailService } from './src/services/emailService';
console.log('13. Importing databaseConfigService...');
import { databaseConfigService } from './src/services/databaseConfigService';
console.log('14. Importing updateChecker...');
import { updateChecker } from './src/services/updateChecker';
console.log('15. Importing routes...');
import apiRoutes from './src/routes';
console.log('DONE: All imports successful');
